spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: '1234'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Hello There World
server:
  port: '8082'