server:
  port: '8083'

spring:
  profiles:
    active: qa

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: '1234'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Hello There World

---
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    password: '1234'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Hello There World

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    password: '1234'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Hello There World
